os: osx
language: node_js
# 初次使用travis ci，做了下面的配置，以为是限制nodejs的版本，#
# 结果travis ci跑了两个build job，分别安装了一个最新的node和一个8的node。
# 所以这里只配置一个就可以了。
node_js:
  - "node"
  # - "8"
branches:
  only:
    - dev
before_script:
  - npm install -g weex-toolkit
install:
  - npm install
script:
  - npm run build:docs
after_success:
  # 注释掉下面的命令，build完后，git push出错了。
  # remote: Anonymous access to FuckDoctors/hello-weex.git denied.
  # fatal: Authentication failed for 'https://@github.com/FuckDoctors/hello-weex.git/'
  - git init
  - git config --global user.name "ujn-bin"
  - git config --global user.email "zhbchwin@163.com"

  # 更新docs
  - git add .
  - git commit -m "Updated by travis-ci at $(date)"
  - git push --force https://$DEPLOY_TOKEN@github.com/FuckDoctors/hello-weex.git dev:dev

  # 哪个地方没设置好，卡在Enter passphrase for id_rsa:
  # 当时生成的时候有没有passphrase忘了。。。加个sshpass -p passphrase试试。
  - echo -e "$SSH_KEY" > id_rsa
  - chmod 600 id_rsa
  - eval $(ssh-agent -s)
  - sshpass -p passphrase ssh-add id_rsa
  - rm -rf id_rsa
  - ssh -o "StrictHostKeyChecking no" git.coding.net

  # 同步zhaobc.coding.me/helle-weex
  - rm -rf ~/coding.net
  - mkdir ~/coding.net
  - cd ~/coding.net
  - git clone https://git.coding.net/zhaobc/zhaobc.coding.me.git
  - rm -rf ./hello-weex
  - cp -R ${TRAVIS_BUILD_DIR}/docs ./hello-weex
  - sed -i '' "s/fuckdoctors.github.io/zhaobc.coding.me/g" `grep "fuckdoctors.github.io" -rl ./hello-weex`
  - git push --force https://git.coding.net/zhaobc/zhaobc.coding.me.git master:master
