os: osx
language: node_js
# 初次使用travis ci，做了下面的配置，以为是限制nodejs的版本，#
# 结果travis ci跑了两个build job，分别安装了一个最新的node和一个8的node。
# 所以这里只配置一个就可以了。
node_js:
  - "node"
  # - "8"
branches:
  only:
    - dev
before_script:
  - npm install -g weex-toolkit
install:
  - npm install
script:
  - npm run build:docs
after_success:
  # 注释掉下面的命令，build完后，git push出错了。
  # remote: Anonymous access to FuckDoctors/hello-weex.git denied.
  # fatal: Authentication failed for 'https://@github.com/FuckDoctors/hello-weex.git/'
  # - git init
  - git config --global user.name "FuckDoctors"
  - git config --global user.email "zhbchwin@163.com"

  # 更新docs
  # 解决Detached head问题
  - git stash
  - git checkout dev
  - git stash pop
  - git add .
  - git commit -m "Updated by travis-ci at $(date)"
  # 发现每次都没提交上来，Everything up-to-date。
  # 后来又仔细看了下log，发现git commit时有[detached HEAD 21a6281]
  # 搜了下，知道了原因。
  # https://stackoverflow.com/questions/10228760/fix-a-git-detached-head
  # Detached head means:
  # (1) You are no longer on a branch,
  # (2) You have checked out a single commit in the history
  - git push --force https://$DEPLOY_TOKEN@github.com/FuckDoctors/hello-weex.git dev:dev

  # 哪个地方没设置好，卡在Enter passphrase for id_rsa:
  # 当时生成的时候有没有passphrase忘了。。。加个sshpass -p passphrase试试。
  # 试了下不行
  # /Users/travis/.travis/job_stages: line 57: sshpass: command not found
  - echo -e "$SSH_KEY" > id_rsa
  - chmod 600 id_rsa
  - eval $(ssh-agent -s)
  - passphrase ssh-add id_rsa
  - rm -rf id_rsa
  # Warning: Permanently added xxx to the list of known hosts.
  # Permission denied (publickey).
  # - ssh -o "StrictHostKeyChecking no" git.coding.net
  - ssh -o "StrictHostKeyChecking no" -o UserKnownHostsFile=/dev/null -o LogLevel=quiet git.coding.net

  # 同步zhaobc.coding.me/helle-weex
  # fatal: Authentication failed for 'https://git.coding.net/zhaobc/zhaobc.coding.me.git/'
  - rm -rf ~/coding.net
  - mkdir ~/coding.net
  - cd ~/coding.net
  - git clone https://git.coding.net/zhaobc/zhaobc.coding.me.git
  - cd ./zhaobc.coding.me
  - rm -rf ./hello-weex
  - cp -R ${TRAVIS_BUILD_DIR}/docs ./hello-weex
  - sed -i '' "s/fuckdoctors.github.io/zhaobc.coding.me/g" `grep "fuckdoctors.github.io" -rl ./hello-weex`
  - git push --force https://git.coding.net/zhaobc/zhaobc.coding.me.git master:master
