os: osx
language: node_js
node_js:
  - "node"

# Travis-CI Caching
# https://docs.travis-ci.com/user/caching/
# cache示例
cache:
  # bundler: true
  # cocoapods: true
  directories:
    # - $HOME/.m2
    - node_modules

branches:
  only:
    - master
before_script:
  # 项目依赖
  - npm install -g weex-toolkit
install:
  - npm install
script:
  - npm run build:docs
after_success:
  # 配置git的用户信息
  - git config --global user.name "FuckDoctors"
  - git config --global user.email "zhbchwin@163.com"

  # 发布到gh-pages分支上
  - cd docs
  - git init
  - git add .
  - git commit -m "Updated by travis-ci at $(TZ='Asia/Shanghai' date "+%Y-%m-%d %H:%M:%S %z")"
  - git push --force https://$DEPLOY_TOKEN@github.com/FuckDoctors/hello-weex.git master:gh-pages
